module.exports = {
  'extends': ['canonical'],
  'rules': {
    'arrow-body-style': [2, 'as-needed'],
    'arrow-parens': 0,
    'babel/arrow-parens': 0,
    'babel/object-curly-spacing': 0,
    'comma-dangle': [2, 'only-multiline'],
    'complexity': 1,
    'computed-property-spacing': 0,
    'func-style': 0,
    'id-length': 0,
    'import/no-namespace': 0,
    'init-declarations': 0,
    'lines-around-comment': 0,
    'max-len': 0,
    'mocha/no-hooks-for-single-case': 0,
    'mocha/no-return-and-callback': 0,
    'newline-after-var': 0,
    'newline-before-return': 0,
    'no-console': 0,
    'no-param-reassign': 0,
    'no-process-env': 0,
    'no-process-exit': 0,
    'no-restricted-syntax': 0,
    'no-shadow': 0,
    'no-use-before-define': 0,
    'object-curly-spacing': 0,
    'object-property-newline': 0,
    'one-var': 0,
    'quotes': [0, 'single'],
    'sort-keys': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 0,
  }
}
